build_macos_task:
  macos_instance:
    image: ghc-12.7-ventura-xcode-15.2

  env:
    MACOSX_DEPLOYMENT_TARGET: "10.13"

  install_node_script:
    - brew install node@20
    - brew link node@20 --force --overwrite

  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
    - source $HOME/.cargo/env && rustup target add x86_64-apple-darwin

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json

  cargo_registry_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat src-tauri/Cargo.lock

  install_deps_script:
    - npm ci

  build_script:
    - source $HOME/.cargo/env
    - npm run tauri build -- --target x86_64-apple-darwin

  dmg_artifacts:
    path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
    type: application/octet-stream
